### ISSUE TITLE
Support for MuMIn

### ISSUE THREAD

**Issue by strengejacke** [strengejacke/sjPlot#352]
see https://github.com/strengejacke/sjmisc/issues/83

**Comment by pratikunterwegs** [comment]
Hi, I was wondering whether there's been an update that covers this issue.
Is one planned?

**Comment by vjjan91** [comment]
Hey! Just checking if there was an update regarding the use of MuMIN 'averaging' objects within sjPlot to model interactions?

**Comment by strengejacke** [comment]
Closing on favour of https://github.com/easystats/parameters/issues/234
(`tab_model()` uses `model_paramters()` under the hood...)

**Comment by pratikunterwegs** [comment]
Thanks for the pointer.

**Comment by strengejacke** [comment]
After updating packages [*insight*](https://easystats.github.io/insight/) and [*parameters*](https://easystats.github.io/parameters/) from GitHub, it should work now.

``` r
library(MuMIn)
library(sjPlot)

data(Cement)
fm1 <- lm(y ~ ., data = Cement, na.action = na.fail)
ms1 <- dredge(fm1)
#> Fixed term is "(Intercept)"

ma <- model.avg(ms1, fit = TRUE)
tab_model(ma)
#> 'r2()' does not support models of class 'averaging'.
```

<table style="border-collapse:collapse; border:none;">

<tr>

<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">

 

</th>

<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">

y

</th>

</tr>

<tr>

<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">

Predictors

</td>

<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">

Estimates

</td>

<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">

CI

</td>

<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">

p

</td>

</tr>

<tr>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">

(Intercept)

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

65.71

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

15.24 – 116.19

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

<strong>0.011</strong>

</td>

</tr>

<tr>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">

X1

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

1.46

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

1.02 – 1.90

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

<strong>\<0.001

</td>

</tr>

<tr>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">

X2

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

0.61

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

0.21 – 1.01

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

<strong>0.003</strong>

</td>

</tr>

<tr>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">

X4

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

\-0.50

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

\-1.08 – 0.08

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

0.091

</td>

</tr>

<tr>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">

X3

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

\-0.07

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

\-1.01 – 0.87

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

0.881

</td>

</tr>

<tr>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">

Observations

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">

13

</td>

</tr>

</table>

<sup>Created on 2020-04-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by vjjan91** [comment]
Just updated it as you suggested, but I still get an error:

devtools::install_github("easystats/insight")
devtools::install_github("easystats/parameters")

ma <- model.avg(ms1, fit = TRUE)
tab_model(ma)

Error: $ operator is invalid for atomic vectors

**Comment by vjjan91** [comment]
I even used the dtupdate package and:

dtupdate::github_update() 

But I get the same error as above.

**Comment by pratikunterwegs** [comment]
@vjjan91's underlying issue is that the `averaging` object was obtained from models of class `unmarked`, specifically using `unmarked::occu()`.
Unmarked support is already an issue, though it references `pcount()`models; I'm not sure how similar they are:  https://github.com/easystats/insight/issues/187#issue-574926355
