### ISSUE TITLE
With sjp.likert, getting warning with odd number of categories, even with cat.neutral defined

### ISSUE THREAD

**Issue by ethulin** [strengejacke/sjPlot#354]
I am trying to use sjp.likert to plot a 5 point likert item. However, when I do so, I get the warning, despite having defined a neutral category:

`Warning message:
Detected uneven category count in items. Dropping last category. `

I get this when running the following code:
`sjp.likert(sample(1:5,100,replace=T),cat.neutral = 3)`

**Comment by strengejacke** [comment]
Yes, that warning is misleading indeed. I'll see if I can fix this.

**Comment by koliajaykr** [comment]
I'm also getting the same warning message. And, on the 5 point Likert scale, the last point is literally not plotted. 

`Warning message:
Detected uneven category count in items. Dropping last category.`

**Comment by strengejacke** [comment]
Yes, for a 5-point scale, without defining a neutral category, the warning is intentional.

**Comment by koliajaykr** [comment]
Thank you for your helpful reply. I made this change `cat.neutral = 3`. Now this neutral point is plotted separately from the other 4 points.

**Comment by strengejacke** [comment]
The reason is simply because a "neutral" category cannot be plotted in a meaningful way. If 30% is "undecided", is this 30% positive _and_ 30% negative? Or, to have a total of 30%, 15% negative and 15% positive?

**Comment by shangeethas** [comment]
Can't we plot 5-point scale without a neutral category ? For example, categories are never, rarely, sometimes, often and very often. In this case, center vertical line is not dividing the likert bars equally. Do you know how to fix this ? Thank you.

**Comment by datasci-iopsy** [comment]
@shangeethas proposes a great question!

**Comment by Taher-Ghaleb** [comment]
`catcount=5` should fix the issue.

**Comment by tjfarrar** [comment]
@Taher-Ghaleb, `catcount=5` does not fix the issue, because it results in an imbalance in the number of "positive" vs. "negative" categories. If the number of categories is odd but there is no true neutral category, one would like to have the middle category straddle the vertical line. Compare the behaviour of `likert.bar.plot` from the `likert` package. A nice fix would be to provide a `logical` option for how to handle the neutral category: either put it off to one side (current default behaviour for `plot_likert`) or have it straddle the vertical line that separates positive from negative categories.
