### ISSUE TITLE
SjPlot: tab_model() for lme() models missing random effects

### ISSUE THREAD

**Issue by martinphilison** [strengejacke/sjPlot#496]
I'm trying to use the function tab_model() to summarize the outout of an lme() model. Unfortunately, the output does not include the random effects structure. Instead, I get the message: "Can't compute random effect variances, verbose = verbose. Some variance components equal zero. Solution: Respecify random structure!" 

However, this is not true. I only included a random intercept in a two-level model and the variance is not zero. Correspondingly, plot_model() does outout random effects of the exact same model fitted using lmer(). Unfortunately, I'll have to use lme() because of other functions it provides exclusively.

Do you have any advice? Thank you in advance!

**Comment by strengejacke** [comment]
Do you have a small reproducible example?

**Comment by martinphilison** [comment]
I can't publish the data but I made a short script using arbitrary data to examplify the problem: lme() models have no output on the random effects, lmer() models have. However, the "Can't compute random effect variances, verbose = verbose. Some variance components equal zero. Solution: Respecify random structure!" is gone in the example (probably because the example is so simple). Please see the .txt for the code attached.

[example.txt](https://github.com/strengejacke/sjPlot/files/3228361/example.txt)

**Comment by strengejacke** [comment]
Thanks, that example is sufficient. I'll look into this.

**Comment by strengejacke** [comment]
I'm not sure if I fixed a bug in between in any of the packages, or if there was another issue, but I can't reproduce your error. Maybe it is solved? Try updating the packages [**insight**](https://github.com/easystats/insight) and [**performance**](https://github.com/easystats/performance) from GitHub, maybe that works?

**Comment by martinphilison** [comment]
Thanks for the reply. I followed your adivce and installed the packages from GitHub. However, the problem persists: tab_model() still doesn't output the random effect part of lme() models. Please find the session Information attached - maybe you can identify what to update? To my knowledge, everything is up to date. 
[session_info.txt](https://github.com/strengejacke/sjPlot/files/3282995/session_info.txt)

**Comment by strengejacke** [comment]
Have you updated sjPlot from GitHub as well?

**Comment by martinphilison** [comment]
Thank you very much, that finally did it :)!

**Comment by strengejacke** [comment]
Not sure, probably by the end of June / beginning of July.

**Comment by almogsi** [comment]
Hi, this is still an issue. I didn't get the "Can't compute random effect variances" message, though; the table included only fixed effects (while it did include random effects with lme4).
I've tried updating insight and performance from GitHub, but when I tried to update sjPlot, I got an error saying something is wrong with performance::principal_components().
Any idea? Many thanks!

**Comment by JamesHMcKay** [comment]
@almogsi I am seeing the same issue, in some cases tab_model does not print out the random effects, using the latest version of sjPlot.  Did you find a fix for your issue?

**Comment by almogsi** [comment]
Hi @JamesHMcKay,
No, I did not.
If I don't need to specify AR terms, I just use lme4::lmer() instead .

**Comment by JamesHMcKay** [comment]
Thanks @almogsi , I have tracked down the issue to the insight::get_variance() function which is called from within tab_model, which is returning NULL in the problematic case, so it looks like it isn't an issue with SjPlot.

**Comment by strengejacke** [comment]
See Note here
https://easystats.github.io/insight/reference/get_variance.html

> Support for objects of class MixMod (GLMMadaptiv) or lme (nlme) is experimental and may not work for all models.

lme() does not return a "user friendly" structure for varcorr().

**Comment by strengejacke** [comment]
You could use glmmTMB for different re-structures like ar or similar. glmmTMB should work.

**Comment by eschrufflim** [comment]
Hi, I had the same issue. The table did not print random effects and R2 (without an error warning) for an lme object (mixed model with AR1). I tried multiple solutions offered online and somehow the issue was fixed when I loaded the package MuMIn. Now the tables produced by tab_model show everything. Might be a solution for others with the same problem when lme4 is not an option.
