### ISSUE TITLE
In tab_model() , the bootstrapping does not work for merMod objects

### ISSUE THREAD

**Issue by nthun** [strengejacke/sjPlot#629]
The `tab_model()` function seems to drop an error if I use the `bootstrap = TRUE` argument, when I use a linear mixed model (lme4). 

```
library(lme4)
library(sjPlot)
mod  <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)
  
sjPlot::tab_model(mod, bootstrap = TRUE)
Error in lme4::bootMer(model, boot_function, nsim = iterations, ...) : 
  unused argument (component = component)
```

I haven't used this function recently, so I'm not sure when it stopped working. 
I tried a random intercept only model, and that failed too.
I tried it with `lm()` and `glm()` and it worked with those.
I use the most recent CRAN versions: `lme4_1.1-23`   `sjPlot_2.8.3`

**Comment by strengejacke** [comment]
Thanks, should work now after updating [paramaters](https://easystats.github.io/parameters):

``` r
library(lme4)
#> Loading required package: Matrix
library(sjPlot)
#> Learn more about sjPlot with 'browseVignettes("sjPlot")'.
mod  <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)
tab_model(mod, bootstrap = TRUE, iterations = 100)
```

<table style="border-collapse:collapse; border:none;">

<tr>

<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">

 

</th>

<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">

Reaction

</th>

</tr>

<tr>

<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">

Predictors

</td>

<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">

Estimates

</td>

<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">

CI

</td>

<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">

p

</td>

</tr>

<tr>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">

(Intercept)

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

250.23

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

237.06 – 266.37

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

<strong>\<0.001

</td>

</tr>

<tr>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">

Days

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

10.48

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

7.34 – 13.25

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">

<strong>\<0.001

</td>

</tr>

<tr>

<td colspan="4" style="font-weight:bold; text-align:left; padding-top:.8em;">

Random Effects

</td>

</tr>

<tr>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">

s<sup>2</sup>

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">

654.94

</td>

<tr>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">

t<sub>00</sub> <sub>Subject</sub>

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">

612.10

</td>

<tr>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">

t<sub>11</sub> <sub>Subject.Days</sub>

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">

35.07

</td>

<tr>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">

<U+03C1><sub>01</sub> <sub>Subject</sub>

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">

0.07

</td>

<tr>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">

ICC

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">

0.72

</td>

<tr>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">

N <sub>Subject</sub>

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">

18

</td>

<tr>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">

Observations

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">

180

</td>

</tr>

<tr>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">

Marginal R<sup>2</sup> / Conditional R<sup>2</sup>

</td>

<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">

0.279 / 0.799

</td>

</tr>

</table>

<sup>Created on 2020-04-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jradinger** [comment]
Bootstrapping CIs of mixed models (tested with _lmer_ at least) seems still not working. This was tested with `sjPlot` version 2.8.9 installed via `devtools::install_github("strengejacke/strengejacke")`.

```
library(lme4)
#devtools::install_github("strengejacke/strengejacke")
library(sjPlot)

mod <- lmer(Reaction ~ Days + (1|Subject), data=sleepstudy)

tab_model(mod)
tab_model(mod,bootstrap = T, iterations = 250)
Error in lme4::bootMer(model, boot_function, nsim = iterations, verbose = FALSE,  : 
  unused argument (component = "conditional")
```

**Comment by Bertramso** [comment]
Dear @strengejacke,

First, thank you very much for your nice contributions to analyze and visualize all kind of statistical models.

When trying to create a model summary for a linear mixed effects model with bootstrap confidence intervals, I get the following error message
Error in match.arg(ci_method, c("hdi", "quantile", "ci", "eti", "si",  : 
  'arg' should be one of “hdi”, “quantile”, “ci”, “eti”, “si”, “bci”, “bcai”
even when using your reproducable example of your previous post:

```r
library(lme4)
#> Loading required package: Matrix
library(sjPlot)
#> Learn more about sjPlot with 'browseVignettes("sjPlot")'.
mod  <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)
tab_model(mod, bootstrap = TRUE, iterations = 100)
```

running R version 4.2.0 with Rstudio 2022.2.3.492 and sjplot version 2.8.10 on Windows 10.

Is this a bug or is there something I can adjust to make it work?

Best wishes,
Bertramso

**Comment by strengejacke** [comment]
I think you need to install the dev-version from GitHub:
Try `devtools::install_github("strengejacke/sjPlot")` and make sure all packages are up to date. For me, your example works fine.

**Comment by Bertramso** [comment]
Thank you very much for your quick reply.
After a previous automatic update of R, some parts got stuck in the old version (rlang and rtools), which prevented the successful installation of all packages required for sjPlot from GitHub.
Now it works just fine. Great!
