### ISSUE TITLE
BRMS Multivariate Ordinal Model - tab_model errors converting 'list' to 'logical'

### ISSUE THREAD

**Issue by JCruk** [strengejacke/sjPlot#677]
I recently re-fit a model for which I was able to generate a summary table, but now when I try I get the following errors:

Error in variance_decomposition(model) :    'list' object cannot be coerced to type 'logical' 
In addition: Warning message: In any(is.mixed) : coercing argument of type 'list' to logical

Is there a trace or anything I can provide? The model is fairly large (132MB)

**Comment by strengejacke** [comment]
This might be due to some internal changes. I _think_ this is fixed in the current GitHub version of sjPlot once you update the _performance_ package.

**Comment by JCruk** [comment]
Unfortunately, the errors persist after updating _performance_ from Github.

**Comment by strengejacke** [comment]
Hm. Do you have a small reproducible example? Maybe on a small subset of your data?

**Comment by strengejacke** [comment]
_bump_

**Comment by JCruk** [comment]
My apologies for the delay!

This is a terrible model, but does effectively reproduce the error, which seems to stem from specifying the number of thresholds:

```
## List required packages ====
Pkgs <- c("tidyverse", "brms", "strengejacke", 
          "rstan")

### Load packages ====
lapply(Pkgs, require, c = T)

## Load data
data <- ordinal::wine %>%
        mutate(Rating1 = rating,
               Rating2 = rating)


fmla <- bf(mvbind(Rating1, Rating2) | resp_thres(4, gr = bottle) ~ temp +
                                            contact +
                                           temp:contact +
                                            (1|o|judge) ) +
        lf(disc ~ 0 + bottle, resp = "Rating1", cmc = FALSE) +
        lf(disc ~ 0 + bottle, resp = "Rating2", cmc = FALSE)
# Compile and fit model ----
mod <- brm(fmla,
            data = data,
            family = cumulative("probit"),
            inits = 0,
            iter = 2000,
            warmup = 1000,
            chains = 2,
            cores = 2,
            sample_prior = TRUE,
            save_all_pars = TRUE)
        )

tab_model(mod,
          transform = NULL,
          string.pred = "Population-Level Effects",
          show.reflvl = TRUE,
          bpe = "median",
          string.est = "Estimate \n(89% CI)",
          show.ci = 0.89,
          collapse.ci = TRUE,
          p.style = NULL,
          show.r2 = FALSE,
          show.re.var = FALSE,
          show.icc = FALSE)

```

**Comment by Crismoc** [comment]
Similar issue using a multivariate model fitted with brms, below a reproducible example with a sample of 3% of the data I'm using (same message when using full data and different model specifications):

``` r
# Data
mdata <- read.csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vQfFJgIlvtiB_Qa79pVWzAF20dhmYhYX2D5NCeSj8ORWm5NbzAgQYGNTTQpZxJG5YiTjHUQfop6jitd/pub?output=csv")

# Packages
library(brms)
#> Loading required package: Rcpp
#> Loading 'brms' package (version 2.14.4). Useful instructions
#> can be found by typing help('brms'). A more detailed introduction
#> to the package is available through vignette('brms_overview').
#> 
#> Attaching package: 'brms'
#> The following object is masked from 'package:stats':
#> 
#>     ar
library(sjPlot)

# Model formula
mf <- mvbf(bf(grspfr | weights(pspwght) ~ isei + agea + eisced + 
                (1|p|cntry)) +
             gaussian(),
           bf(netifr | weights(pspwght) ~ isei + agea + eisced + 
                (1|p|cntry)) +
             gaussian(),
           rescor = TRUE)

# Fit model
m <- brm(mf,
         prior = c(prior(lkj(1), class = rescor)),
         data = mdata, chains = 2)
#> Compiling Stan program...
#> Trying to compile a simple C file
#> Running /usr/lib/R/bin/R CMD SHLIB foo.c
#> gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG   -I"/home/c/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include/"  -I"/home/c/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/"  -I"/home/c/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/unsupported"  -I"/home/c/R/x86_64-pc-linux-gnu-library/4.0/BH/include" -I"/home/c/R/x86_64-pc-linux-gnu-library/4.0/StanHeaders/include/src/"  -I"/home/c/R/x86_64-pc-linux-gnu-library/4.0/StanHeaders/include/"  -I"/home/c/R/x86_64-pc-linux-gnu-library/4.0/RcppParallel/include/"  -I"/home/c/R/x86_64-pc-linux-gnu-library/4.0/rstan/include" -DEIGEN_NO_DEBUG  -DBOOST_DISABLE_ASSERTS  -DBOOST_PENDING_INTEGER_LOG2_HPP  -DSTAN_THREADS  -DBOOST_NO_AUTO_PTR  -include '/home/c/R/x86_64-pc-linux-gnu-library/4.0/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp'  -D_REENTRANT -DRCPP_PARALLEL_USE_TBB=1      -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-8T8CYO/r-base-4.0.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c foo.c -o foo.o
#> In file included from /home/c/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/Eigen/Core:88,
#>                  from /home/c/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/Eigen/Dense:1,
#>                  from /home/c/R/x86_64-pc-linux-gnu-library/4.0/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp:13,
#>                  from <command-line>:
#> /home/c/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/Eigen/src/Core/util/Macros.h:613:1: error: unknown type name ‘namespace’
#>   613 | namespace Eigen {
#>       | ^~~~~~~~~
#> /home/c/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/Eigen/src/Core/util/Macros.h:613:17: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
#>   613 | namespace Eigen {
#>       |                 ^
#> In file included from /home/c/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/Eigen/Dense:1,
#>                  from /home/c/R/x86_64-pc-linux-gnu-library/4.0/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp:13,
#>                  from <command-line>:
#> /home/c/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/Eigen/Core:96:10: fatal error: complex: No such file or directory
#>    96 | #include <complex>
#>       |          ^~~~~~~~~
#> compilation terminated.
#> make: *** [/usr/lib/R/etc/Makeconf:172: foo.o] Error 1
#> Start sampling
#> 
#> SAMPLING FOR MODEL '8e954028afba102d5eda6035e47ad06c' NOW (CHAIN 1).
#> Chain 1: 
#> Chain 1: Gradient evaluation took 0.000481 seconds
#> Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 4.81 seconds.
#> Chain 1: Adjust your expectations accordingly!
#> Chain 1: 
#> Chain 1: 
#> Chain 1: Iteration:    1 / 2000 [  0%]  (Warmup)
#> Chain 1: Iteration:  200 / 2000 [ 10%]  (Warmup)
#> Chain 1: Iteration:  400 / 2000 [ 20%]  (Warmup)
#> Chain 1: Iteration:  600 / 2000 [ 30%]  (Warmup)
#> Chain 1: Iteration:  800 / 2000 [ 40%]  (Warmup)
#> Chain 1: Iteration: 1000 / 2000 [ 50%]  (Warmup)
#> Chain 1: Iteration: 1001 / 2000 [ 50%]  (Sampling)
#> Chain 1: Iteration: 1200 / 2000 [ 60%]  (Sampling)
#> Chain 1: Iteration: 1400 / 2000 [ 70%]  (Sampling)
#> Chain 1: Iteration: 1600 / 2000 [ 80%]  (Sampling)
#> Chain 1: Iteration: 1800 / 2000 [ 90%]  (Sampling)
#> Chain 1: Iteration: 2000 / 2000 [100%]  (Sampling)
#> Chain 1: 
#> Chain 1:  Elapsed Time: 48.2132 seconds (Warm-up)
#> Chain 1:                12.3963 seconds (Sampling)
#> Chain 1:                60.6095 seconds (Total)
#> Chain 1: 
#> 
#> SAMPLING FOR MODEL '8e954028afba102d5eda6035e47ad06c' NOW (CHAIN 2).
#> Chain 2: 
#> Chain 2: Gradient evaluation took 0.000446 seconds
#> Chain 2: 1000 transitions using 10 leapfrog steps per transition would take 4.46 seconds.
#> Chain 2: Adjust your expectations accordingly!
#> Chain 2: 
#> Chain 2: 
#> Chain 2: Iteration:    1 / 2000 [  0%]  (Warmup)
#> Chain 2: Iteration:  200 / 2000 [ 10%]  (Warmup)
#> Chain 2: Iteration:  400 / 2000 [ 20%]  (Warmup)
#> Chain 2: Iteration:  600 / 2000 [ 30%]  (Warmup)
#> Chain 2: Iteration:  800 / 2000 [ 40%]  (Warmup)
#> Chain 2: Iteration: 1000 / 2000 [ 50%]  (Warmup)
#> Chain 2: Iteration: 1001 / 2000 [ 50%]  (Sampling)
#> Chain 2: Iteration: 1200 / 2000 [ 60%]  (Sampling)
#> Chain 2: Iteration: 1400 / 2000 [ 70%]  (Sampling)
#> Chain 2: Iteration: 1600 / 2000 [ 80%]  (Sampling)
#> Chain 2: Iteration: 1800 / 2000 [ 90%]  (Sampling)
#> Chain 2: Iteration: 2000 / 2000 [100%]  (Sampling)
#> Chain 2: 
#> Chain 2:  Elapsed Time: 46.2167 seconds (Warm-up)
#> Chain 2:                14.257 seconds (Sampling)
#> Chain 2:                60.4737 seconds (Total)
#> Chain 2:

# Model table
tab_model(m)
#> Warning in any(is.mixed): coercing argument of type 'list' to logical
#> Error in performance::variance_decomposition(model): 'list' object cannot be coerced to type 'logical'
```

<sup>Created on 2020-12-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
@Crismoc Thanks! I have fixed this issue (located in the [performance-package](https://easystats.github.io/performance)), so it should now work _after updating_ [insight](https://easystats.github.io/insight) and [performance](https://easystats.github.io/performance) from GitHub.

**Comment by strengejacke** [comment]
@JCruk your initial issue is resolved, so it should work now. The warning still remains, but can be ignored. I'm trying to fix it.
