### ISSUE TITLE
sjPlot plot_model not displaying interaction names

### ISSUE THREAD

**Issue by eimichae85** [strengejacke/sjPlot#888]
Hi there,

I am running a generalised linear mixed model with a lot of factors and their interactions.
`mod1<-glmer(cbind(branch_miner_Yes,branch_miner_No)~ Drought+Stratum+Year+Drought:Stratum+Drought:Year+Stratum:Year+(1|Tree.ID)+(1|Sample.ID),
      data=Herb1920, family=binomial(),na.action = na.exclude)`

I want to visualise the model estimations with a forest plot. Using the following code:
`Eplot_Miner<-plot_model(mod1, vline.color = "gray",   colors = c("black","black"),sort.est=F,show.values = TRUE, value.offset = .45,value.size = 6,title = "",  dot.size=5.3, line.size =0.8 ,transform = NULL,order.terms = c(1,3, 2, 5,4,6))+
  theme_classic()+
  theme(axis.text=element_text(face="bold",size=18),
        axis.title = element_text(color="black",face="bold",size=19),
        axis.line = element_line(colour = 'black', size = 1),
        axis.ticks = element_line(colour = "black", size = 1),
        legend.text=element_text(size=14),
        legend.title=element_text(size=15, face="bold"),
        plot.title = element_text(color="black", size=18, face="bold"))

Eplot_Miner`

However, for some reason plot_model won't show the interaction terms on the y axis, it just says "conditional" for all of them (see picture).
![Rplot](https://user-images.githubusercontent.com/104637782/225648284-64f01109-0d67-464e-bfbb-406e4b47a9a0.jpeg)

I realized that the problem only apperars witha glmer but not with a glmmTMB model.

**Comment by strengejacke** [comment]
Do you have a small dataset to reproduce this issue, or any other (fake) example that reproduces this issue?

**Comment by eimichae85** [comment]
I streamlined the code a bit. any idea why the problem with the "conditional" labelling exists?

**Comment by strengejacke** [comment]
I have a guess, but let me look into this later. I'm currently preparing the CRAN submission of _parameters_, which is internally used by _sjPlot_, so I can resolve this issue once I submitted _parameters_.

**Comment by strengejacke** [comment]
Should be fixed in _parameters_:

``` r
library(parameters)
library(lme4)
library(sjPlot)
library(ggplot2)
load("d:/mail/test.RData")
Eplot_Miner <- plot_model(mod, vline.color = "gray", colors = c("black", "black"), sort.est = F, show.values = TRUE, value.offset = .45, value.size = 6, title = "", dot.size = 5.3, line.size = 0.8, transform = NULL, order.terms = c(1, 3, 2, 5, 4, 6)) +
  theme_classic() +
  theme(
    axis.text = element_text(face = "bold", size = 18),
    axis.title = element_text(color = "black", face = "bold", size = 19),
    axis.line = element_line(colour = "black", size = 1),
    axis.ticks = element_line(colour = "black", size = 1),
    legend.text = element_text(size = 14),
    legend.title = element_text(size = 15, face = "bold"),
    plot.title = element_text(color = "black", size = 18, face = "bold")
  )
Eplot_Miner
```

![](https://i.imgur.com/phbRDFK.png)

<sup>Created on 2023-03-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by eimichae85** [comment]
Yes, fantastic!
Thanks a lot for fixing this issue so quickly

**Comment by eimichae85** [comment]
Hi,
thank you for working on this.
Unfortunately I still have the same problem.
I updated my R-version (4.2.3) and all my packages: e.g. sJPlot(2.8.13) , parameters (0.20.2) etc.

Only two packages could not be updated: robustbase and cli but I guess that is not the problem. What to do?

**Comment by strengejacke** [comment]
The fixes are on github only, but both packages will be updated on CRAN the next days. If you don't want to wait, try:

```r
remotes::install_github("strengejacke/sjPlot")
remotes::install_github("easystats/parameters")
```

**Comment by eimichae85** [comment]
Ah apparently I was not patient enough:)
It works with the updated packages. Thanks a lot for fixing this issue so quickly!

**Comment by eimichae85** [comment]
Sorry I have another follow-up isssue that may be related to the package update.
I realized that the "vilne" ( "zero effect" line) is now much narrower now that it used to be. this is a problem because now 3/4 of my figures have a wide-zero effect line and 1/4 has a narrow line

(see exaples below):

![wide](https://user-images.githubusercontent.com/104637782/230757639-2d4973c2-5eac-4618-b7c1-da76ddc059f7.png)
![narrow](https://user-images.githubusercontent.com/104637782/230757642-23c3a8d5-db2c-4d8f-8c13-04169df152bf.png)

For the love of my life I could not find a way to make this line wider. Is this somehow possible?

Thanks a lot!
